<?php

namespace ContainerW2Y4Luq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RXdq9myService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RXdq9my' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RXdq9my'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AnimalController::afficher_animal' => ['privates', '.service_locator.4ZNRFs3', 'get_ServiceLocator_4ZNRFs3Service', true],
            'App\\Controller\\AnimalController::index' => ['privates', '.service_locator.SJ5L2VQ', 'get_ServiceLocator_SJ5L2VQService', true],
            'App\\Controller\\ContinentController::afficherContinent' => ['privates', '.service_locator.Uw0H8PX', 'get_ServiceLocator_Uw0H8PXService', true],
            'App\\Controller\\ContinentController::index' => ['privates', '.service_locator.pvjBq8n', 'get_ServiceLocator_PvjBq8nService', true],
            'App\\Controller\\FamilleController::afficherFamille' => ['privates', '.service_locator.RDs2.4K', 'get_ServiceLocator_RDs2_4KService', true],
            'App\\Controller\\FamilleController::index' => ['privates', '.service_locator.BNZq2gZ', 'get_ServiceLocator_BNZq2gZService', true],
            'App\\Controller\\PersonneController::index' => ['privates', '.service_locator.M.9MdJ.', 'get_ServiceLocator_M_9MdJ_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\AnimalController:afficher_animal' => ['privates', '.service_locator.4ZNRFs3', 'get_ServiceLocator_4ZNRFs3Service', true],
            'App\\Controller\\AnimalController:index' => ['privates', '.service_locator.SJ5L2VQ', 'get_ServiceLocator_SJ5L2VQService', true],
            'App\\Controller\\ContinentController:afficherContinent' => ['privates', '.service_locator.Uw0H8PX', 'get_ServiceLocator_Uw0H8PXService', true],
            'App\\Controller\\ContinentController:index' => ['privates', '.service_locator.pvjBq8n', 'get_ServiceLocator_PvjBq8nService', true],
            'App\\Controller\\FamilleController:afficherFamille' => ['privates', '.service_locator.RDs2.4K', 'get_ServiceLocator_RDs2_4KService', true],
            'App\\Controller\\FamilleController:index' => ['privates', '.service_locator.BNZq2gZ', 'get_ServiceLocator_BNZq2gZService', true],
            'App\\Controller\\PersonneController:index' => ['privates', '.service_locator.M.9MdJ.', 'get_ServiceLocator_M_9MdJ_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\AnimalController::afficher_animal' => '?',
            'App\\Controller\\AnimalController::index' => '?',
            'App\\Controller\\ContinentController::afficherContinent' => '?',
            'App\\Controller\\ContinentController::index' => '?',
            'App\\Controller\\FamilleController::afficherFamille' => '?',
            'App\\Controller\\FamilleController::index' => '?',
            'App\\Controller\\PersonneController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AnimalController:afficher_animal' => '?',
            'App\\Controller\\AnimalController:index' => '?',
            'App\\Controller\\ContinentController:afficherContinent' => '?',
            'App\\Controller\\ContinentController:index' => '?',
            'App\\Controller\\FamilleController:afficherFamille' => '?',
            'App\\Controller\\FamilleController:index' => '?',
            'App\\Controller\\PersonneController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
