<?php

namespace ContainerW2Y4Luq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RDs2_4KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RDs2.4K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RDs2.4K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'famille' => ['privates', '.errored..service_locator.RDs2.4K.App\\Entity\\Famille', NULL, 'Cannot autowire service ".service_locator.RDs2.4K": it references class "App\\Entity\\Famille" but no such service exists.'],
        ], [
            'famille' => 'App\\Entity\\Famille',
        ]);
    }
}
