<?php

namespace ContainerW2Y4Luq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContinentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Uw0H8PX.App\Entity\Continent' shared service.
     *
     * @return \App\Entity\Continent
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Uw0H8PX": it references class "App\\Entity\\Continent" but no such service exists.');
    }
}
