<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQzBSfAv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQzBSfAv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQzBSfAv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQzBSfAv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQzBSfAv\App_KernelDevDebugContainer([
    'container.build_hash' => 'QzBSfAv',
    'container.build_id' => '54cdc1b6',
    'container.build_time' => 1597826095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQzBSfAv');
